GET http://localhost:5000

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"jjkml",
    "password": "TestPassword123"

}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "jjkml",
    "password": "TestPassword123"

}


###
POST http://localhost:5000/shorten
Content-Type: application/json

{
    "url":"https://www.youtube.com/watch?v=mGrVmEex6_g"

}